language: python

python:
    - 3.3
    - 3.4

env:
    matrix:
        - PYTHONASYNCIODEBUG=1
        - PYTHONASYNCIODEBUG=0

before_script:
    - "mysql -e 'DROP DATABASE IF EXISTS test_pymysql; create database test_pymysql  DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"
    - "mysql -e 'DROP DATABASE IF EXISTS test_pymysql2; create database test_pymysql2 DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'"

install:
    - pip install git+https://github.com/PyMySQL/PyMySQL.git@master
    - pip install flake8
    - pip install sqlalchemy
    - pip install nose
    - pip install coverage
    - pip install .
    - pip install coveralls

script:
  - make cov

after_success:
  - coveralls
